"""
PDF Document Engine & Invoice Generator Connector.
Uses fpdf2 to generate branded customer invoices, order summaries, and PDF spec sheets,
and pypdf for parsing document text.
"""

from typing import Any, Dict, List, Optional
from pathlib import Path
from datetime import datetime
from fpdf import FPDF

from agentic_ai.connectors.base import BaseConnector


class InvoicePDF(FPDF):
    """Custom PDF class with branded header and footer."""

    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(30, 41, 59)
        self.cell(0, 10, "TECH STORE - OFFICIAL ORDER INVOICE", border=False, align="L", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(59, 130, 246)
        self.set_line_width(0.8)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by Product Query AI Agent", align="C")


class PDFConnector(BaseConnector):
    """
    Connector for generating PDF documents, invoices, quotations, and parsing PDF files.
    """

    def __init__(self, output_dir: Optional[str] = None, name: str = "PDFConnector"):
        super().__init__(
            name=name,
            description="Connector for generating customer PDF invoices, quotations, and reading PDF documents using fpdf2 and pypdf."
        )
        self.output_dir = Path(output_dir or "invoices")

    def connect(self) -> bool:
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self._is_connected = True
        return True

    def disconnect(self) -> None:
        self._is_connected = False

    def generate_invoice_pdf(
        self,
        customer_name: str,
        items: List[Dict[str, Any]],
        discount_code: Optional[str] = None,
        discount_amount: float = 0.0,
        shipping_cost: float = 0.0,
        tax_amount: float = 0.0,
    ) -> Dict[str, Any]:
        """
        Generate a PDF invoice and return file details and download path.
        """
        if not self.is_connected:
            self.connect()

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        invoice_number = f"INV-{timestamp[-8:]}"
        filename = f"{invoice_number}.pdf"
        file_path = self.output_dir / filename

        pdf = InvoicePDF(orientation="P", unit="mm", format="A4")
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()

        # Metadata Section
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(71, 85, 105)
        pdf.cell(100, 6, f"Invoice #: {invoice_number}", ln=False)
        pdf.cell(0, 6, f"Date: {datetime.now().strftime('%B %d, %Y')}", ln=True, align="R")
        pdf.cell(100, 6, f"Customer: {customer_name}", ln=False)
        pdf.cell(0, 6, "Payment Status: Confirmed / Pre-Authorized", ln=True, align="R")
        pdf.ln(6)

        # Table Header
        pdf.set_fill_color(241, 245, 249)
        pdf.set_text_color(15, 23, 42)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(90, 8, "Item Description", border=1, fill=True)
        pdf.cell(25, 8, "Qty", border=1, align="C", fill=True)
        pdf.cell(35, 8, "Unit Price", border=1, align="R", fill=True)
        pdf.cell(40, 8, "Total", border=1, align="R", fill=True, ln=True)

        # Table Rows
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(51, 65, 85)
        subtotal = 0.0

        for item in items:
            name = str(item.get("name", "Product"))[:45]
            qty = int(item.get("qty", 1))
            price = float(item.get("price", 0.0))
            line_total = qty * price
            subtotal += line_total

            pdf.cell(90, 7, name, border=1)
            pdf.cell(25, 7, str(qty), border=1, align="C")
            pdf.cell(35, 7, f"${price:.2f}", border=1, align="R")
            pdf.cell(40, 7, f"${line_total:.2f}", border=1, align="R", ln=True)

        pdf.ln(4)

        # Totals calculation
        grand_total = subtotal - discount_amount + shipping_cost + tax_amount

        # Summary Breakdown
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(120, 6, "", border=False)
        pdf.cell(35, 6, "Subtotal:", border=0, align="R")
        pdf.cell(35, 6, f"${subtotal:.2f}", border=0, align="R", ln=True)

        if discount_amount > 0:
            pdf.set_text_color(220, 38, 38)
            pdf.cell(120, 6, "", border=False)
            pdf.cell(35, 6, f"Discount ({discount_code or 'PROMO'}):", border=0, align="R")
            pdf.cell(35, 6, f"-${discount_amount:.2f}", border=0, align="R", ln=True)
            pdf.set_text_color(51, 65, 85)

        pdf.cell(120, 6, "", border=False)
        pdf.cell(35, 6, "Shipping:", border=0, align="R")
        pdf.cell(35, 6, f"${shipping_cost:.2f}" if shipping_cost > 0 else "FREE", border=0, align="R", ln=True)

        if tax_amount > 0:
            pdf.cell(120, 6, "", border=False)
            pdf.cell(35, 6, "Estimated Tax:", border=0, align="R")
            pdf.cell(35, 6, f"${tax_amount:.2f}", border=0, align="R", ln=True)

        pdf.ln(2)
        pdf.set_draw_color(15, 23, 42)
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(120, 8, "", border=False)
        pdf.cell(35, 8, "GRAND TOTAL:", border="T", align="R")
        pdf.cell(35, 8, f"${grand_total:.2f}", border="T", align="R", ln=True)

        # Output file
        pdf.output(str(file_path))

        return {
            "status": "success",
            "invoice_number": invoice_number,
            "filename": filename,
            "file_path": str(file_path),
            "grand_total_usd": grand_total,
            "generated_at": datetime.now().isoformat(),
        }
