"""
Product Catalog Knowledge Base for Product Query Agent.
Contains structured product inventory, specifications, pricing, stock levels, and promotional discounts.
"""

from typing import Any, Dict, List, Optional

PRODUCTS: List[Dict[str, Any]] = [
    {
        "id": "PROD-101",
        "name": "Apple MacBook Air M3",
        "brand": "Apple",
        "category": "Laptops",
        "price": 1099.00,
        "currency": "USD",
        "stock": 18,
        "rating": 4.8,
        "reviews_count": 1240,
        "specs": {
            "processor": "Apple M3 8-core CPU",
            "gpu": "10-core GPU",
            "ram": "16GB Unified Memory",
            "storage": "512GB SSD",
            "display": "13.6-inch Liquid Retina display (2560x1664)",
            "battery_life": "Up to 18 hours",
            "weight": "1.24 kg (2.7 lbs)",
            "colors": ["Midnight", "Starlight", "Space Gray", "Silver"],
        },
        "description": "Super-fast Apple M3 chip laptop with fanless quiet design, stunning display, and all-day battery life.",
        "warranty": "1 Year Limited Apple Warranty",
        "warehouse_location": "US-East (New Jersey)",
        "estimated_shipping_days": 2,
    },
    {
        "id": "PROD-102",
        "name": "Dell XPS 14 (2024)",
        "brand": "Dell",
        "category": "Laptops",
        "price": 1499.00,
        "currency": "USD",
        "stock": 7,
        "rating": 4.5,
        "reviews_count": 520,
        "specs": {
            "processor": "Intel Core Ultra 7 155H",
            "gpu": "NVIDIA GeForce RTX 4050 (6GB GDDR6)",
            "ram": "32GB LPDDR5X",
            "storage": "1TB PCIe NVMe SSD",
            "display": "14.5-inch 3.2K OLED Touchscreen (120Hz)",
            "battery_life": "Up to 12 hours",
            "weight": "1.68 kg (3.7 lbs)",
            "colors": ["Platinum", "Graphite"],
        },
        "description": "Premium ultraportable laptop with vibrant 3.2K OLED display, dedicated RTX graphics, and sleek aluminum chassis.",
        "warranty": "2 Years Onsite Dell Care",
        "warehouse_location": "US-Central (Texas)",
        "estimated_shipping_days": 3,
    },
    {
        "id": "PROD-103",
        "name": "Lenovo ThinkPad X1 Carbon Gen 12",
        "brand": "Lenovo",
        "category": "Laptops",
        "price": 1349.00,
        "currency": "USD",
        "stock": 12,
        "rating": 4.7,
        "reviews_count": 890,
        "specs": {
            "processor": "Intel Core Ultra 7 165U",
            "gpu": "Intel Arc Graphics",
            "ram": "16GB LPDDR5X",
            "storage": "512GB PCIe Gen4 SSD",
            "display": "14.0-inch 2.8K OLED (2880x1800, 120Hz)",
            "battery_life": "Up to 14 hours",
            "weight": "1.09 kg (2.42 lbs)",
            "colors": ["Deep Black Carbon Fiber"],
        },
        "description": "The gold standard of business laptops. Ultra-lightweight carbon fiber body, legendary keyboard, and military-grade durability.",
        "warranty": "3 Years Lenovo Premier Support",
        "warehouse_location": "US-West (California)",
        "estimated_shipping_days": 2,
    },
    {
        "id": "PROD-104",
        "name": "Acer Swift Go 14",
        "brand": "Acer",
        "category": "Laptops",
        "price": 699.00,
        "currency": "USD",
        "stock": 25,
        "rating": 4.4,
        "reviews_count": 430,
        "specs": {
            "processor": "Intel Core Ultra 5 125H",
            "gpu": "Intel Arc Graphics",
            "ram": "16GB LPDDR5",
            "storage": "512GB PCIe Gen4 SSD",
            "display": "14.0-inch 2.8K OLED (90Hz)",
            "battery_life": "Up to 10 hours",
            "weight": "1.32 kg (2.9 lbs)",
            "colors": ["Silver"],
        },
        "description": "Best budget OLED productivity laptop. Crisp display, high value performance, and full port selection.",
        "warranty": "1 Year Limited Warranty",
        "warehouse_location": "US-Central (Illinois)",
        "estimated_shipping_days": 3,
    },
    {
        "id": "PROD-201",
        "name": "Apple iPhone 16 Pro",
        "brand": "Apple",
        "category": "Smartphones",
        "price": 999.00,
        "currency": "USD",
        "stock": 35,
        "rating": 4.9,
        "reviews_count": 3100,
        "specs": {
            "processor": "A18 Pro chip",
            "camera": "48MP Main + 48MP Ultra-Wide + 12MP 5x Telephoto",
            "display": "6.3-inch Super Retina XDR with ProMotion (120Hz)",
            "storage": "256GB / 512GB / 1TB",
            "battery": "Up to 27 hours video playback",
            "build": "Grade 5 Titanium with Ceramic Shield front",
            "colors": ["Desert Titanium", "Natural Titanium", "White Titanium", "Black Titanium"],
        },
        "description": "Flagship iPhone featuring Grade 5 Titanium design, dedicated Camera Control button, 4K 120 fps Dolby Vision recording, and Apple Intelligence.",
        "warranty": "1 Year Apple Limited Warranty",
        "warehouse_location": "US-East (New Jersey)",
        "estimated_shipping_days": 1,
    },
    {
        "id": "PROD-202",
        "name": "Samsung Galaxy S25 Ultra",
        "brand": "Samsung",
        "category": "Smartphones",
        "price": 1199.00,
        "currency": "USD",
        "stock": 20,
        "rating": 4.8,
        "reviews_count": 2150,
        "specs": {
            "processor": "Snapdragon 8 Elite for Galaxy",
            "camera": "200MP Main + 50MP 5x Telephoto + 50MP Ultra-Wide + 10MP 3x Telephoto",
            "display": "6.9-inch Dynamic AMOLED 2X, QHD+ (120Hz, 3000 nits)",
            "storage": "256GB / 512GB / 1TB",
            "battery": "5000 mAh (45W Fast Charging)",
            "build": "Titanium Frame with Gorilla Glass Armor",
            "colors": ["Titanium Gray", "Titanium Black", "Titanium Silver Blue"],
        },
        "description": "Ultimate Android flagship with integrated S Pen, anti-reflective display, 200MP pro camera with 100x Space Zoom, and Galaxy AI suite.",
        "warranty": "1 Year Samsung Care Standard",
        "warehouse_location": "US-Central (Texas)",
        "estimated_shipping_days": 2,
    },
    {
        "id": "PROD-203",
        "name": "Google Pixel 9 Pro",
        "brand": "Google",
        "category": "Smartphones",
        "price": 899.00,
        "currency": "USD",
        "stock": 15,
        "rating": 4.7,
        "reviews_count": 1420,
        "specs": {
            "processor": "Google Tensor G4 with Titan M2 security coprocessor",
            "camera": "50MP Main + 48MP Quad PD Ultra-Wide + 48MP 5x Telephoto",
            "display": "6.3-inch Super Actua display (1-120Hz LTPO OLED)",
            "storage": "128GB / 256GB / 512GB",
            "battery": "4700 mAh (24+ hour battery life)",
            "build": "Polished aluminum frame, matte glass back",
            "colors": ["Obsidian", "Porcelain", "Hazel", "Rose Quartz"],
        },
        "description": "Compact pro smartphone with class-leading computational photography, 7 years of OS updates, and native Gemini Nano AI features.",
        "warranty": "1 Year Google Hardware Warranty",
        "warehouse_location": "US-West (California)",
        "estimated_shipping_days": 2,
    },
    {
        "id": "PROD-301",
        "name": "Sony WH-1000XM5",
        "brand": "Sony",
        "category": "Audio",
        "price": 348.00,
        "currency": "USD",
        "stock": 42,
        "rating": 4.8,
        "reviews_count": 4890,
        "specs": {
            "type": "Over-Ear Wireless Active Noise Cancelling",
            "battery_life": "30 hours (ANC On), 40 hours (ANC Off)",
            "bluetooth": "Bluetooth 5.2 (LDAC, AAC, SBC)",
            "anc": "Dual processor Auto NC Optimizer with 8 microphones",
            "weight": "250g",
            "features": ["Multipoint Connection", "Speak-to-Chat", "Wearing Detection"],
            "colors": ["Black", "Silver", "Midnight Blue"],
        },
        "description": "Industry-leading active noise cancelling headphones with superior sound clarity, crystal clear calling, and ultra-comfortable lightweight fit.",
        "warranty": "1 Year Sony Manufacturer Warranty",
        "warehouse_location": "US-East (New Jersey)",
        "estimated_shipping_days": 1,
    },
    {
        "id": "PROD-302",
        "name": "Bose QuietComfort Ultra",
        "brand": "Bose",
        "category": "Audio",
        "price": 379.00,
        "currency": "USD",
        "stock": 28,
        "rating": 4.7,
        "reviews_count": 2780,
        "specs": {
            "type": "Over-Ear Wireless Noise Cancelling",
            "battery_life": "24 hours (18 hours with Immersive Audio)",
            "bluetooth": "Bluetooth 5.3 (Snapdragon Sound, aptX Adaptive)",
            "anc": "CustomTune technology with World-Class Noise Cancellation",
            "weight": "252g",
            "features": ["Bose Immersive Audio Spatialized Sound", "Custom Modes", "Multipoint"],
            "colors": ["Black", "White Smoke", "Sandstone"],
        },
        "description": "Exceptional comfort and breakthrough spatialized audio with unmatched active noise cancellation.",
        "warranty": "1 Year Bose Warranty",
        "warehouse_location": "US-Central (Texas)",
        "estimated_shipping_days": 2,
    },
    {
        "id": "PROD-303",
        "name": "Apple AirPods Pro (2nd Gen, USB-C)",
        "brand": "Apple",
        "category": "Audio",
        "price": 229.00,
        "currency": "USD",
        "stock": 60,
        "rating": 4.9,
        "reviews_count": 9400,
        "specs": {
            "type": "In-Ear True Wireless ANC Earbuds",
            "chip": "H2 Headphone Chip",
            "battery_life": "6 hours per charge (30 hours total with MagSafe USB-C case)",
            "anc": "2x more Active Noise Cancellation + Adaptive Audio & Transparency Mode",
            "rating_ip": "IP54 dust, sweat, and water resistant",
            "features": ["Personalized Spatial Audio", "Conversation Awareness", "Precision Finding Case"],
            "colors": ["White"],
        },
        "description": "The quintessential wireless earbuds for Apple users with next-generation ANC, Adaptive Audio, and USB-C MagSafe case.",
        "warranty": "1 Year Apple Limited Warranty",
        "warehouse_location": "US-East (New Jersey)",
        "estimated_shipping_days": 1,
    },
    {
        "id": "PROD-401",
        "name": "LG UltraGear 34GS95QE-B OLED Gaming Monitor",
        "brand": "LG",
        "category": "Monitors",
        "price": 999.00,
        "currency": "USD",
        "stock": 9,
        "rating": 4.6,
        "reviews_count": 310,
        "specs": {
            "size": "34-inch Curved (800R)",
            "panel": "OLED (UltraWide QHD 3440 x 1440)",
            "refresh_rate": "240Hz",
            "response_time": "0.03ms (GtG)",
            "color_gamut": "DCI-P3 98.5% (VESA DisplayHDR True Black 400)",
            "ports": ["2x HDMI 2.1", "1x DisplayPort 1.4", "2x USB 3.0 Up/Down"],
        },
        "description": "High-end ultrawide 800R curved gaming monitor with 240Hz refresh rate and near-instantaneous 0.03ms response time.",
        "warranty": "2 Years LG Panel & Parts Warranty (OLED burn-in coverage included)",
        "warehouse_location": "US-West (California)",
        "estimated_shipping_days": 4,
    },
    {
        "id": "PROD-402",
        "name": "Dell UltraSharp 27 4K USB-C Hub Monitor (U2723QE)",
        "brand": "Dell",
        "category": "Monitors",
        "price": 549.00,
        "currency": "USD",
        "stock": 14,
        "rating": 4.8,
        "reviews_count": 1120,
        "specs": {
            "size": "27-inch Flat",
            "panel": "IPS Black Technology (4K UHD 3840 x 2160, 60Hz)",
            "contrast_ratio": "2000:1",
            "color_gamut": "100% sRGB, 98% DCI-P3",
            "ports": ["USB-C 90W Power Delivery", "RJ45 Ethernet", "DisplayPort 1.4", "HDMI 2.0", "5x USB-A"],
        },
        "description": "Premier productivity monitor for creatives and professionals with IPS Black contrast technology and built-in 90W USB-C hub.",
        "warranty": "3 Years Dell Advanced Exchange Service",
        "warehouse_location": "US-Central (Texas)",
        "estimated_shipping_days": 3,
    },
    {
        "id": "PROD-501",
        "name": "Apple Watch Ultra 2",
        "brand": "Apple",
        "category": "Smartwatches",
        "price": 749.00,
        "currency": "USD",
        "stock": 16,
        "rating": 4.9,
        "reviews_count": 1650,
        "specs": {
            "case_size": "49mm Aerospace Titanium Case",
            "display": "3000 nits Always-On Retina Display with Sapphire Front",
            "battery_life": "Up to 36 hours (72 hours in Low Power Mode)",
            "water_resistance": "100m water resistant (EN13319 dive certified up to 40m)",
            "sensors": ["Precision Dual-frequency GPS", "ECG", "Blood Oxygen", "Depth Gauge", "Water Temperature"],
            "colors": ["Natural Titanium", "Black Titanium"],
        },
        "description": "The ultimate sports and adventure smartwatch built for endurance athletes, outdoor exploration, and water sports.",
        "warranty": "1 Year Apple Limited Warranty",
        "warehouse_location": "US-East (New Jersey)",
        "estimated_shipping_days": 1,
    },
    {
        "id": "PROD-502",
        "name": "Garmin Fenix 8 (47mm AMOLED)",
        "brand": "Garmin",
        "category": "Smartwatches",
        "price": 999.00,
        "currency": "USD",
        "stock": 8,
        "rating": 4.8,
        "reviews_count": 680,
        "specs": {
            "case_size": "47mm Titanium Bezel with Sapphire Crystal",
            "display": "1.4-inch AMOLED Touchscreen",
            "battery_life": "Up to 16 days in smartwatch mode",
            "water_resistance": "100m with leakproof inductive buttons & dive support up to 40m",
            "sensors": ["Multi-band SatIQ GPS", "Wrist-based Heart Rate", "Pulse Ox", "Built-in LED Flashlight", "Voice Speaker/Mic"],
            "colors": ["Titanium with Orange Band", "Carbon Gray DLC Titanium"],
        },
        "description": "Multi-sport GPS smartwatch engineered with brilliant AMOLED display, built-in flashlight, speaker/mic, and advanced training metrics.",
        "warranty": "2 Years Garmin Manufacturer Warranty",
        "warehouse_location": "US-Central (Kansas)",
        "estimated_shipping_days": 2,
    },
]

DISCOUNTS: List[Dict[str, Any]] = [
    {
        "code": "TECHSAVINGS10",
        "description": "10% off any laptop or monitor purchase over $500",
        "discount_percent": 10,
        "valid_categories": ["Laptops", "Monitors"],
        "min_spend": 500.00,
    },
    {
        "code": "AUDIOBOOST",
        "description": "$30 instant rebate on Sony and Bose headphones",
        "discount_fixed": 30.00,
        "valid_categories": ["Audio"],
        "min_spend": 200.00,
    },
    {
        "code": "FLAGSHIP100",
        "description": "$100 instant trade-in discount on iPhone 16 Pro and Galaxy S25 Ultra",
        "discount_fixed": 100.00,
        "valid_categories": ["Smartphones"],
        "min_spend": 800.00,
    },
    {
        "code": "SUMMERSALE15",
        "description": "15% storewide discount for all electronics",
        "discount_percent": 15,
        "valid_categories": ["Laptops", "Smartphones", "Audio", "Monitors", "Smartwatches"],
        "min_spend": 100.00,
    },
]
